; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
lib_deps = 
	m5stack/M5Unified@^0.2.13
	m5stack/M5Cardputer@^1.1.1
	tanakamasayuki/EspHttpServer@^1.0.1

build_flags = -std=gnu++17
build_unflags = -std=gnu++11

[env:native]
platform = native
test_build_src = yes
build_src_filter = +<*> -<main.cpp> -<state.cpp> -<ui.cpp> -<captive.cpp>
build_flags = 
    -D NATIVE_BUILD
    -I wasm
    -std=c++11
test_filter = test_native

[env:cardputer]
platform = espressif32
board = m5stack-cardputer
framework = arduino
test_speed = 115200
test_filter = test_esp32